new Vue({
  el:'#app',
  data(){
    return{
      menus:[
        {
          label:'商品追加・更新・削除',
          path:'merchandise/merchandise.html'
        },
        {
          label:'会員管理',
          path:'merchandise/user.html'
        },
        {
          label:'売上管理',
          path:'merchandise/Earnings.html'
        },
        {
          label:'商品・在庫検索',
          path:'merchandise/contact.html'
        }
      ]
    };
  }
})